name: fit_in_room
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  navigation:
    path: ./navigation
  all_rooms:
    path: ./features/all_rooms
  test_history:
    path: ./features/test_history
  home:
    path: ./features/home
  room_detail:
    path: ./features/room_detail
  settings:
    path: ./features/settings
  add_room:
    path: ./features/add_room

  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_gen:

flutter:
  uses-material-design: true

  fonts:
    - family: SofiaSans
      fonts:
        - asset: assets/fonts/SofiaSans-Bold.ttf
          weight: 900