name: core_ui
version: 0.0.1
publish_to: none
description: Project Core UI module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  fonts:
    - family: SofiaSans
      fonts:
        - asset: ../assets/fonts/SofiaSans-Bold.ttf
          weight: 900